In [7]:
from sklearn import datasets

# load iris dataset
iris = datasets.load_iris()

In [8]:
import pandas as pd

# since this is a bunch, create a dataframe
iris_df=pd.DataFrame(iris.data)
iris_df['class']=iris.target
iris_df.columns=['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid', 'class']
iris_df.dropna(how="all", inplace=True) # remove any empty lines

#view the iris dataframe
print(iris_df['class'][51])

1


In [35]:
import numpy as np

# Define our neural network class
class NeuralNetwork:
    def __init__(self, input_size, hidden_size, output_size):
        # Hidden layer initialization
        np.random.seed(42)
        self.W1 = np.random.rand(input_size, hidden_size)
        self.b1 = np.zeros((1, hidden_size))

        # Output layer initialization
        self.W2 = np.random.rand(hidden_size, output_size)
        self.b2 = np.zeros((1, output_size))

    def sigmoid(self, z):
        return 1 / (1 + np.exp(-z))

    def relu(self, x):
        return np.maximum(0, x)

    def softmax(self, x):
        """Compute softmax values for each sets of scores in x."""
        # Subtract the max value from each score to prevent overflow in exp
        e_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
        return e_x / e_x.sum(axis=-1, keepdims=True)

    def forward(self, x):
        # calculate the activations in the hidden layer
        self.Z1 = np.dot(x, self.W1) + self.b1
        self.A1 = self.relu(self.Z1)

        # calculate activations for the output layer
        self.Z2 = np.dot(self.A1, self.W2) + self.b2
        y_hat = self.softmax(self.Z2)
        return y_hat

In [38]:
# create a new instance of a neural network
nn = NeuralNetwork(input_size = 4, hidden_size = 8, output_size = 3)

X = iris_df[['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid']].values
#print(X)

y_hat = nn.forward(X)

print(y_hat)
# print(y_hat[:5])
# print(y_hat[145:])

Y = iris_df['class'].values.reshape(-1, 1)  # Reshape for consistency
#print(Y)

[[8.25183092e-01 9.73829540e-03 1.65078612e-01]
 [8.36204221e-01 1.17377573e-02 1.52058022e-01]
 [8.06040062e-01 1.34198187e-02 1.80540119e-01]
 [8.10412494e-01 1.42261024e-02 1.75361404e-01]
 [8.11560837e-01 1.03527707e-02 1.78086392e-01]
 [8.37678343e-01 7.05334768e-03 1.55268309e-01]
 [7.89877540e-01 1.36825711e-02 1.96439889e-01]
 [8.26118890e-01 1.04346148e-02 1.63446495e-01]
 [8.01215908e-01 1.68525743e-02 1.81931518e-01]
 [8.33475931e-01 1.17359446e-02 1.54788124e-01]
 [8.40344417e-01 7.63739505e-03 1.52018188e-01]
 [8.13507402e-01 1.18877460e-02 1.74604852e-01]
 [8.27803676e-01 1.28551312e-02 1.59341193e-01]
 [7.73579262e-01 1.87813750e-02 2.07639362e-01]
 [8.44383833e-01 5.77585533e-03 1.49840312e-01]
 [8.26775247e-01 5.56519582e-03 1.67659557e-01]
 [8.24729074e-01 7.37352518e-03 1.67897401e-01]
 [8.25952689e-01 9.54814932e-03 1.64499161e-01]
 [8.62361171e-01 5.83925303e-03 1.31799576e-01]
 [8.12550580e-01 9.18307738e-03 1.78266343e-01]
 [8.60618666e-01 7.64875050e-03 1.317325