In [10]:
from sklearn import datasets
import pandas as pd
import numpy as np

# load iris dataset
iris = datasets.load_iris()

# since this is a bunch, create a dataframe
iris_df=pd.DataFrame(iris.data)
iris_df['class']=iris.target
iris_df.columns=['sepal_len', 'sepal_wid', 'petal_len', 'petal_wid', 'class']
iris_df.dropna(how="all", inplace=True) # remove any empty lines

print(iris_df)


     sepal_len  sepal_wid  petal_len  petal_wid  class
0          5.1        3.5        1.4        0.2      0
1          4.9        3.0        1.4        0.2      0
2          4.7        3.2        1.3        0.2      0
3          4.6        3.1        1.5        0.2      0
4          5.0        3.6        1.4        0.2      0
..         ...        ...        ...        ...    ...
145        6.7        3.0        5.2        2.3      2
146        6.3        2.5        5.0        1.9      2
147        6.5        3.0        5.2        2.0      2
148        6.2        3.4        5.4        2.3      2
149        5.9        3.0        5.1        1.8      2

[150 rows x 5 columns]


In [26]:
inputLayerSize = 4
hiddenLayerSize = 8
outputLayerSize = 3

In [48]:
# Random Weight

# First Random Weight matrix Input to Hidden layers
W1 = np.random.rand(hiddenLayerSize, inputLayerSize)
# First Random Weight matrix Hidden to Output layers 
W2 = np.random.rand(outputLayerSize, hiddenLayerSize)
print(W1)
print(" ")
print(W2)

[[0.8359929  0.04377293 0.93373356 0.84296813]
 [0.41337967 0.95927489 0.95516153 0.04555595]
 [0.30152866 0.32845921 0.59567272 0.53964447]
 [0.30679836 0.36642388 0.79843557 0.44404882]
 [0.47404939 0.86291363 0.10742296 0.8106241 ]
 [0.46298523 0.80491773 0.34365313 0.50692951]
 [0.69682609 0.85283356 0.07915453 0.19745055]
 [0.72504537 0.96279694 0.9830814  0.7943539 ]]
 
[[0.44627374 0.93686845 0.9728287  0.13432685 0.05895633 0.38345359
  0.5207814  0.51166993]
 [0.45790776 0.89029982 0.89814957 0.75024143 0.16371903 0.37928741
  0.84385727 0.34901862]
 [0.28621917 0.60669242 0.98921577 0.06115837 0.67903111 0.04856148
  0.83354633 0.62637431]]


In [49]:
# Starting Bias for hidden layer
b1 = np.zeros((hiddenLayerSize, 1))
# Starting Bias for hidden layer
b2 = np.zeros((outputLayerSize, 1))
print(b1)
print(" ")
print(b2)


[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
 
[[0.]
 [0.]
 [0.]]


    Implements the ReLU activation function.
    
    Arguments:
    Z -- Output of the linear layer, of any shape

    Returns:
    A -- Post-activation parameter, of the same shape as Z
    cache -- a python dictionary containing "A" ; stored for computing the backward pass efficiently

In [50]:
 def ActivationFunction_relu(Z):
    A = np.maximum(0, Z)
    assert(A.shape == Z.shape)
    cache = {"A": A}
    return A, cache

Implement the linear part of a layer's forward propagation.

    Arguments:
    A_prev -- activations from previous layer (or input data): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)

    Returns:
    Z -- the input of the activation function, also called pre-activation parameter
    cache -- a python dictionary containing "A_prev", "W" and "b" ; stored for computing the backward pass efficiently

In [51]:
def linear_forward(A_prev, W, b):
    Z = W.dot(A_prev) + b
    assert(Z.shape == (W.shape[0], A_prev.shape[1]))
    cache = {"A_prev": A_prev, "W": W, "b": b}
    return Z, cache

    Implements the ReLU activation function.
    
    Arguments:
    Z -- Output of the linear layer, of any shape

    Returns:
    A -- Post-activation parameter, of the same shape as Z
    cache -- a python dictionary containing "A" ; stored for computing the backward pass efficiently

In [55]:
def relu(Z):
    A = np.maximum(0, Z)
    assert(A.shape == Z.shape)
    cache = {"A": A}
    return A, cache

 
    Implement forward propagation for the LINEAR->ACTIVATION layer

    Arguments:
    A_prev -- activations from previous layer (or input data): (size of previous layer, number of examples)
    W -- weights matrix: numpy array of shape (size of current layer, size of previous layer)
    b -- bias vector, numpy array of shape (size of the current layer, 1)

    Returns:
    A -- the output of the activation function, also called the post-activation value
    cache -- a python tuple containing "linear_cache" and "activation_cache";
             stored for computing the backward pass efficiently

In [56]:
def forward_propagation(A_prev, W, b):
    Z, linear_cache = linear_forward(A_prev, W, b)
    A, activation_cache = relu(Z)
    cache = (linear_cache, activation_cache)
    return A, cache
   

In [57]:
# Sample input
X = np.random.randn(4, 1) # 4 features, 1 example

In [58]:
# Forward propagation from input to hidden layer
A1, cache1 = forward_propagation(X, W1, b1)

In [59]:
# Forward propagation from hidden layer to output
A2, cache2 = forward_propagation(A1, W2, b2)


In [60]:
print("Output of the network:", A2)

Output of the network: [[0.17583526]
 [0.18041915]
 [0.11277254]]


 
    Implement the backward propagation for a single RELU unit.

    Arguments:
    dA -- post-activation gradient, of any shape
    cache -- 'Z' where we store for computing backward propagation efficiently

    Returns:
    dZ -- Gradient of the cost with respect to Z
    

In [ ]:
def relu_backward(dA, cache):
    Z = cache
    dZ = np.array(dA, copy=True)  # just converting dz to a correct object.
    dZ[Z <= 0] = 0  # When z <= 0, you should set dz to 0 as well.
    return dZ

    Implement the linear portion of backward propagation for a single layer (layer l)

    Arguments:
    dZ -- Gradient of the cost with respect to the linear output (of current layer l)
    cache -- tuple of values (A_prev, W, b) coming from the forward propagation in the current layer

    Returns:
    dA_prev -- Gradient of the cost with respect to the activation (of the previous layer l-1), same shape as A_prev
    dW -- Gradient of the cost with respect to W (current layer l), same shape as W
    dB -- Gradient of the cost with respect to b (current layer l), same shape as b

### Linear backward

In [ ]:
def linear_backward(dZ, cache):
    A_prev, W, b = cache['A_prev'], cache['W'], cache['b']
    m = A_prev.shape[1]

    dW = 1./m * np.dot(dZ, A_prev.T)
    db = 1./m * np.sum(dZ, axis=1, keepdims=True)
    dA_prev = np.dot(W.T, dZ)
    
    return dA_prev, dW, db

Implement the backward propagation for LINEAR->RELU->LINEAR->RELU->LINEAR->SIGMOID
    
    Arguments:
    dA2 -- post-activation gradient for output
    cache2 -- cache stored during forward propagation for the second LINEAR->RELU step
    cache1 -- cache stored during forward propagation for the first LINEAR->RELU step
    
    Returns:
    grads -- A dictionary with the gradients dA1, dW2, db2, dW1, db1

### Compute the Categorical Cross-Entropy Loss

In [ ]:
def compute_loss(Y, Y_hat):
    m = Y.shape[1]
    loss = -np.sum(Y * np.log(Y_hat)) / m
    return loss

    Implement the backward propagation for the last layer using softmax and Categorical Cross-Entropy
    
    Arguments:
    dZ -- Gradient of the loss with respect to the output of the last linear layer (Z)
    cache2 -- cache stored during forward propagation for the second LINEAR->RELU step
    cache1 -- cache stored during forward propagation for the first LINEAR->RELU step
    
    Returns:
    grads -- A dictionary with the gradients dA1, dW2, db2, dW1, db1

In [ ]:
def backward_propagation_with_softmax(dZ, cache2, cache1):
    # Assuming cache2 and cache1 include the necessary caches for the respective layers
    dA1, dW2, db2 = linear_backward(dZ, cache2["linear"])
    
    linear_cache1, activation_cache1 = cache1
    dZ1 = relu_backward(dA1, activation_cache1['A'])
    dA0, dW1, db1 = linear_backward(dZ1, linear_cache1)
    
    grads = {"dA1": dA1, "dW2": dW2, "db2": db2, "dW1": dW1, "db1": db1}
    return grads

In [ ]:
def backward_propagation(dA2, cache2, cache1):
    linear_cache2, activation_cache2 = cache2
    dZ2 = relu_backward(dA2, activation_cache2['A'])
    dA1, dW2, db2 = linear_backward(dZ2, linear_cache2)
    
    linear_cache1, activation_cache1 = cache1
    dZ1 = relu_backward(dA1, activation_cache1['A'])
    dA0, dW1, db1 = linear_backward(dZ1, linear_cache1)
    
    grads = {"dA1": dA1, "dW2": dW2, "db2": db2, "dW1": dW1, "db1": db1}
    return grads

In [ ]:
def update_parameters(parameters, grads, learning_rate):
    parameters["W1"] -= learning_rate * grads["dW1"]
    parameters["b1"] -= learning_rate * grads["db1"]
    parameters["W2"] -= learning_rate * grads["dW2"]
    parameters["b2"] -= learning_rate * grads["db2"]
    return parameters

### MODEL

In [ ]:
def model(X, Y, n_h, num_iterations=1000, learning_rate=0.01):
    n_x = X.shape[0]
    n_y = Y.shape[0]
    
    for i in range(num_iterations):
        # Forward propagation
        A1, cache1 = forward_propagation(X, W1, b1)
        A2, cache2 = softmax(np.dot(W2, A1) + b2)
        
        # Compute loss
        loss = compute_loss(Y, A2)
        
        # Backward propagation
        dZ2 = A2 - Y
        grads = backward_propagation_with_softmax(dZ2, cache2, cache1)
        
        # Update parameters
        parameters = update_parameters(parameters, grads, learning_rate)
        
        if i % 100 == 0:
            print("Loss after iteration %i: %f" %(i, loss))
    
    return parameters